agregado ejercicio broker
teamcubation/sandbox-byma pull request #4
Opened 2024-09-16 14:14 UTC by maxizeta

2024-09-18 12:40 UTC, DamianMarquezMeli requested changes

2024-09-18 12:40 UTC, DamianMarquezMeli commented on Max/src/main/java/axi/Broker.java
> +    }
Hay 2 propiedades que podrian ser una misma, tenemos una constante que se asigna a otra propuedad, ambas de la misma clase, podemos juntar estas dos en una misma

```suggestion
    private static Broker broker;
    private String name = "AXI";
    private ArrayList<InstrumentoFinanciero> instrumentos;
    private ArrayList<Inversor>inversores;

    private Broker() {
        this.instrumentos = new ArrayList<>();
        this.inversores = new ArrayList<>();
    }
```

2024-09-18 12:40 UTC, DamianMarquezMeli commented on Max/src/main/java/axi/Broker.java
> +        return inversor;
La utulizar un foreach es mas sencillo de leer el procedimiento de este metodo, si utilizamos un for regular tenemos que indicar con mayor fuerza el valor de la variable que itera

```suggestion
        Inversor inversor = null;
        for (int indice = 0; indice < inversores.size(); indice++) {
            if (inversores.get(indice).getDni().equals(dni))
                inversor = inversores.get(indice);
        }
        return inversor;
```

2024-09-18 12:40 UTC, DamianMarquezMeli commented on Max/src/main/java/axi/Broker.java
> +        }
iterando con un ForEach nos ahorramos validar si es vacia o no la lista, por lo que el if inicial estaria de mas

```suggestion
       
            for (InstrumentoFinanciero instrumento : instrumentos) {
                System.out.println(instrumento);
            }
       
```

2024-09-18 12:40 UTC, DamianMarquezMeli commented on Max/src/main/java/axi/Broker.java
> +                    }
hacer un try catch, manejar la excepcion pero luego no tirar otra exception dentro de un flujo de proceso, no es 100% correcto pero es para tenerlo en cuenta a esto para mas adelante.

2024-09-18 12:40 UTC, DamianMarquezMeli commented on Max/src/main/java/axi/modelos/InstrumentoFinancieroFactory.java
> +        }
como este factory tiene tendencia a crecer por lo que lo mejor es hacer esto un swtich.

2024-09-20 18:04 UTC, julianmarcelolopez requested changes
Buenas Maxi, veo bastante bien el codigo. Te dejo algunos comentarios mas. 
Muy bueno!

2024-09-20 18:04 UTC, julianmarcelolopez commented on Max/src/main/java/axi/servicios/InstrumentoService.java
> +        if (instrumento != null) {
Me parece algo compleja la logica, yo le pasaria los campos y setearia todos los campos de nuevo, validando que ningun campo sea nulo.

2024-09-20 18:04 UTC, julianmarcelolopez commented on Max/src/main/java/axi/servicios/InstrumentoService.java
> +            throw new InversorNoEncontradoException("Error. Instrumento no encontrado");
Siempre es mejor validar por el negado al principio o sea: 

```java
if (instrumento == null)
      throw new InversorNoEncontradoException("Error. Instrumento no encontrado");
``` 

.... sigue toda la logica de modify

2024-09-20 20:36 UTC, merged