primeros avances del gestor de acciones y bonos
teamcubation/sandbox-byma pull request #7
Opened 2024-09-16 19:49 UTC by Lucia-azd

2024-09-18 12:26 UTC, DamianMarquezMeli commented on Lu/src/main/java/Controlador/Controlador.java
> +        vista.mensaje("\n-------- Se registro exitosamente el intrumento financiero: --------\n" + instrumentoFinanciero.toString());
Como hablamos, la ides es que los mensajes los configure la Vista y desde el controller solo se devuelva el resultado del proceso principalmente.

2024-09-18 12:26 UTC, DamianMarquezMeli commented on Lu/src/main/java/Controlador/Controlador.java
> +        double precio = vista.getPrecio();
Si bien esta perfecto el tema de que la Vista es la que obtiene el input,tener centralizado esta llamada a la vista en un metodo puntual en el controller puede prevenir futuras refatorizaciones.

```suggestion
        int instrumentoFinancieroTipo = ObtenerTipo();
        String nombre = ObtenerNombre();
        double precio = ObtenerPrecio();
```

2024-09-18 12:26 UTC, DamianMarquezMeli commented on Lu/src/main/java/Enums/MenuConsultar.java
> +}
Es debatible el tema de los Enums en si, no esta mal pero la pregunta que yo me haria si un enum es una clase o una clase es un enum? :|

Para charlarlo a ver que les parece a los demas inicialmente

2024-09-20 18:23 UTC, julianmarcelolopez requested changes
Genial Lu, veo que estructuraste teniendo en cuenta la arquitectura de capas. Te dejo algunos comentarios.

2024-09-20 18:23 UTC, julianmarcelolopez commented on Lu/src/main/java/controlador/Controlador.java
> +    private final Vista vista;
Sabes que hace el final aca?

2024-09-20 18:23 UTC, julianmarcelolopez commented on Lu/src/main/java/repository/InstrumentoFinancieroRepository.java
> +    List<InstrumentoFinanciero> instrumentosFinancieros;
Como buena practica este atributo debe ser private tambien. Ya que esta lista solo puede ser accedida o modificada por el Repository.

2024-09-20 18:23 UTC, julianmarcelolopez commented on Lu/src/main/java/repository/InstrumentoFinancieroRepository.java
> +        instrumentosFinancieros = Singleton.getInstancia();
La implementacion de Singleton la dejaria especificamente en Repository, estaria de mas la clase Singleton.

2024-09-20 18:23 UTC, julianmarcelolopez commented on Lu/src/main/java/repository/InstrumentoFinancieroRepository.java
> +        instrumentosFinancieros.removeIf(instrumentoFinancieroAEliminar -> instrumentoFinancieroAEliminar.getNombre().equals(nombre));
Este rremoveIf esta algo redundante ya que ya tenes el elemento a eliminar: 
instrumentosFinancieros.remove(instrumentoFinanciero);

2024-09-20 18:23 UTC, julianmarcelolopez commented on Lu/src/main/java/repository/singleton/Singleton.java
> +public class Singleton {
Por lo que veo esta clase esta de mas.

2024-09-20 18:23 UTC, julianmarcelolopez commented on Lu/src/main/java/service/InstrumentoFinancieroService.java
> +    public InstrumentoFinanciero eliminar(String nombre) throws InstrumentoNoEncontradoException {
Esta ok, solo que el encargado de buscar el elemento y validar si existe antes de eliminarlo es el Service.

Dejo un ejemplo: 

```java
public void eliminar(String nombre) throws InstrumentoNoEncontradoException {
        Optional<InstrumentoFinanciero> instrumentoFinanciero = instrumentosFinancierosRepository.buscarPorNombre(nombre);

        if (instrumentoFinanciero.isEmpty()) {
            throw new InstrumentoNoEncontradoException("Instrumento financiero inexistente.");
        }

        instrumentosFinancierosRepository.eliminar(nombre); 
    }

```

2024-09-20 18:36 UTC, Lucia-azd commented on Lu/src/main/java/controlador/Controlador.java
> +    private final Vista vista;
El ide me tiro un warning y queria dejar el archivo sin ningun warning jajaj

2024-09-20 20:18 UTC, DamianMarquezMeli approved these changes

2024-09-20 20:19 UTC, DamianMarquezMeli approved these changes

2024-09-20 20:19 UTC, merged